apiVersion: v1
kind: Service
metadata:
  labels:
    node: {{ .Values.opengemini.metaSqlStore.name }}
  name: {{ .Values.opengemini.metaSqlStore.name }}-nodeport
  namespace: {{ .Values.opengemini.namespace }}
spec:
  ports:
    - name: sql
      port: 8086
      protocol: TCP
      targetPort: 8086
      nodePort: {{ .Values.opengemini.metaSqlStore.sqlNodePort }}
  selector:
    node: {{ .Values.opengemini.metaSqlStore.name }}
  sessionAffinity: None
  type: NodePort