apiVersion: v1
kind: Service
metadata:
  labels:
    node: {{ .Values.opengemini.metaStore.name }}
  name: {{ .Values.opengemini.metaStore.name }}
  namespace: {{ .Values.opengemini.namespace }}
spec:
  ports:
    - name: store-write
      port: 8400
    - name: store-query
      port: 8401
    - name: meta-8092
      port: 8092
    - name: meta-8091
      port: 8091
    - name: store-8011
      port: 8011
    - name: meta-8010
      port: 8010
    - name: meta-8088
      port: 8088      
  selector:
    node: {{ .Values.opengemini.metaStore.name }}
  sessionAffinity: None
