{{- range .Values.opengemini.sqlStore.nodeNames }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ . }}-data-pvc
  namespace: {{ $.Values.opengemini.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ $.Values.opengemini.storageClassName }}
  resources:
    requests:
      storage: {{ $.Values.opengemini.sqlStore.dataStorageSize }}
{{- end }}      