name: Build openGemini docker image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Choose vesion'
        required: true
        default: 'v2'
        type: choice
        options:
        - v1
        - v2

jobs:
  build-opengemini-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      
    - name: Build the openGemini v1 Docker image
      if: inputs.version == 'v1'
      run: echo v1


    - name: Build the openGemini v2 Docker image
      if: inputs.version == 'v1'
      run: echo v2